version: '3.9'

services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hackathon
    ports:
      - '5432:5432'
    volumes:
      - hackathon_data:/var/lib/postgresql/data

volumes:
  hackathon_data:
